# Generated by Django 5.2.16 on 2026-07-22 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Responsable boutique'), ('CATALOG', 'Gestionnaire catalogue'), ('SALES', 'Commercial B2B'), ('SUPPORT', 'Service client'), ('DELIVERY', 'Livreur')], default='SUPPORT', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='intitulé de poste')),
                ('delivery_zone', models.CharField(blank=True, max_length=120, verbose_name='zone de livraison')),
                ('vehicle', models.CharField(blank=True, max_length=60, verbose_name='véhicule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employé',
                'verbose_name_plural': 'employés',
                'ordering': ('-created_at',),
            },
        ),
    ]
