# Generated by Django 5.2.16 on 2026-07-31 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sales_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('SALE', 'Vente'), ('RESTOCK', 'Réapprovisionnement'), ('RETURN', 'Retour client / Annulation'), ('CORRECTION', 'Ajustement inventaire')], default='CORRECTION', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
